### ISSUE TITLE
ng build --watch keep rebuilding

### ISSUE THREAD

**Issue by sic-sic** [alexzuza/angular-plugin-architecture#43]
Coud someone explain me why I can't build a plugin in --watch mode

when i run: `ng build --project plugins --aot --modulePath=./plugin1/plugin1.module#Plugin1Module --pluginName=plugin1 --sharedLibs=shared --outputPath=./src/assets/plugins --watch`

without making any changes the plugin keep rebuilding every second :
<img width="762" alt="Screen Shot 2021-03-20 at 12 28 25" src="https://user-images.githubusercontent.com/14206274/111869536-f0437b80-8977-11eb-9293-b5fa931847cc.png">

**Comment by john-gouda** [comment]
@sic-sic because of that line here:

https://github.com/alexzuza/angular-plugin-architecture/blob/9df09f3780261ddbf292ce1584d06258f3db90a1/builders/plugin-builder/index.ts#L108 

If you use Angular 9+ and Ivy enabled, no factories required, hence you don't need to patch main.ts during build time.
The loop you see is builder change main.ts contents which trigger the watcher to rebuild.
It's really nice implementation enjoy it!
Good luck!

**Comment by sic-sic** [comment]
@jfgouda Thanks a lot for the hint.
I am using Angular 9+ and Ivy enabled, do you think it's really necessary to use the custom builder `builders/plugin-builder/index.ts` can't I afford it with ng-packagr ?

**Comment by john-gouda** [comment]
If you modified the builder logic and remove patch main, and rely on manual exports in main.ts you should be fine. What builder currently does, is exporting the module and it's factory before Ivy, since doesn't generate factory files and it embed them in a static property so the concept of patching main.ts not needed.

BTW, builder is producing the plugin as an application, check angular.json project plugin-builder is of type application not a library.

Through WebPack configs you dropping dependencies such as ng core, rxjs etc

**Comment by sic-sic** [comment]
It's much clear for me now. Thank you
